<% db_socket = ENV['DEV_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  password: zm7IN77wbnGOVpGo7AVcxqCC
  socket: <%= db_socket %>

development:
  <<: *default
  username: root
  database: nabatheon-server_development
  password:

test:
  <<: *default
  username: root
  database: nabatheon-server_test
  password:

# production:
#   <<: *default
#   database: nabatheon-server_production
#   username: nabatheon-server

